import { ConveyorData } from '../types/conveyor';

export const DEFAULT_CONVEYOR_DATA: ConveyorData = {
  Id: 1,
  ConveyorNodes: [
    {
      Id: "0",
      XPosition: -3.24,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
    {
      Id: "1",
      XPosition: -2.0,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
    {
      Id: "2",
      XPosition: -0.8,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
    {
      Id: "3",
      XPosition: 0.8,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
    {
      Id: "4",
      XPosition: 2.2,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
    {
      Id: "5",
      XPosition: 3.24,
      ZPosition: 0.0,
      TangentMode: 1,
      YRotation: 90.0,
    },
  ],
  ConveyorRoute: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
  ],
  ConveyorSlots: [
    {
      Id: "0",
      TargetNodeId: "1",
      YRotation: 90.0,
      XPosition: -1.95,
      ZPosition: 2.0,
      LockedTurn: 0,
      UnlockedByAd: false,
    },
    {
      Id: "1",
      TargetNodeId: "2",
      YRotation: 90.0,
      XPosition: -0.65,
      ZPosition: 2.0,
      LockedTurn: 0,
      UnlockedByAd: false,
    },
    {
      Id: "2",
      TargetNodeId: "3",
      YRotation: 90.0,
      XPosition: 0.65,
      ZPosition: 2.0,
      LockedTurn: 0,
      UnlockedByAd: false,
    },
    {
      Id: "3",
      TargetNodeId: "4",
      YRotation: 90.0,
      XPosition: 1.95,
      ZPosition: 2.0,
      LockedTurn: 0,
      UnlockedByAd: false,
    },
  ],
  IsLoop: false,
  BoardOffsetX: 0.0,
  BoardOffsetZ: 2.0,
  NumberOfArrows: 3,
};
